title: Uku Taht
email: uku.taht@gmail.com
description: Uku Taht's development blog
baseurl: ""
url: "http://yourdomain.com"
twitter_username: ukutaht
github_username:  heruku

markdown: redcarpet

permalink: none
