title: Uku Taht
email: uku.taht@gmail.com
description: Uku Taht's development blog
baseurl: ""
url: "http://yourdomain.com"
twitter_username: ukutaht
github_username:  ukutaht

kramdown:
  input: GFM

permalink: none
